### ISSUE TITLE
Post title should allow shorter

### ISSUE THREAD

**Issue by bkdev98** [duongdev/golb#11]
That being said, my 4 characters title not valid to publish.
<img width="604" alt="Screen Shot 2020-08-07 at 08 54 00" src="https://user-images.githubusercontent.com/16166195/89600235-ba8bcf80-d88b-11ea-8a11-0ead279ec5c8.png">

**Comment by duongdev** [comment]
Should I set the `min` value to `1`?

**Comment by bkdev98** [comment]
Yes I guess

**Comment by duongdev** [comment]
@bkdev98 Do you think we should limit the max-length if the title?
